// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AlertAttribute extends pulumi.CustomResource {
    /**
     * Get an existing AlertAttribute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertAttributeState, opts?: pulumi.CustomResourceOptions): AlertAttribute {
        return new AlertAttribute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/alertAttribute:AlertAttribute';

    /**
     * Returns true if the given object is an instance of AlertAttribute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlertAttribute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlertAttribute.__pulumiType;
    }

    /**
     * Whether this attribute is an array
     */
    declare public readonly array: pulumi.Output<boolean>;
    /**
     * The emoji to display alongside this attribute in chat messages, stored without colons
     */
    declare public readonly emoji: pulumi.Output<string | undefined>;
    /**
     * Unique name of this attribute
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Whether this attribute is required. If this field is not set, the existing setting will be preserved.
     */
    declare public readonly required: pulumi.Output<boolean>;
    /**
     * Engine resource name for this attribute
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a AlertAttribute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertAttributeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertAttributeArgs | AlertAttributeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertAttributeState | undefined;
            resourceInputs["array"] = state?.array;
            resourceInputs["emoji"] = state?.emoji;
            resourceInputs["name"] = state?.name;
            resourceInputs["required"] = state?.required;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as AlertAttributeArgs | undefined;
            if (args?.array === undefined && !opts.urn) {
                throw new Error("Missing required property 'array'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["array"] = args?.array;
            resourceInputs["emoji"] = args?.emoji;
            resourceInputs["name"] = args?.name;
            resourceInputs["required"] = args?.required;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AlertAttribute.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AlertAttribute resources.
 */
export interface AlertAttributeState {
    /**
     * Whether this attribute is an array
     */
    array?: pulumi.Input<boolean>;
    /**
     * The emoji to display alongside this attribute in chat messages, stored without colons
     */
    emoji?: pulumi.Input<string>;
    /**
     * Unique name of this attribute
     */
    name?: pulumi.Input<string>;
    /**
     * Whether this attribute is required. If this field is not set, the existing setting will be preserved.
     */
    required?: pulumi.Input<boolean>;
    /**
     * Engine resource name for this attribute
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AlertAttribute resource.
 */
export interface AlertAttributeArgs {
    /**
     * Whether this attribute is an array
     */
    array: pulumi.Input<boolean>;
    /**
     * The emoji to display alongside this attribute in chat messages, stored without colons
     */
    emoji?: pulumi.Input<string>;
    /**
     * Unique name of this attribute
     */
    name?: pulumi.Input<string>;
    /**
     * Whether this attribute is required. If this field is not set, the existing setting will be preserved.
     */
    required?: pulumi.Input<boolean>;
    /**
     * Engine resource name for this attribute
     */
    type: pulumi.Input<string>;
}
