// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AlertRoute extends pulumi.CustomResource {
    /**
     * Get an existing AlertRoute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertRouteState, opts?: pulumi.CustomResourceOptions): AlertRoute {
        return new AlertRoute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/alertRoute:AlertRoute';

    /**
     * Returns true if the given object is an instance of AlertRoute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlertRoute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlertRoute.__pulumiType;
    }

    /**
     * Which alert sources should this alert route match?
     */
    declare public readonly alertSources: pulumi.Output<outputs.AlertRouteAlertSource[]>;
    /**
     * The channel configuration for this alert route
     */
    declare public readonly channelConfigs: pulumi.Output<outputs.AlertRouteChannelConfig[] | undefined>;
    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    declare public readonly conditionGroups: pulumi.Output<outputs.AlertRouteConditionGroup[]>;
    /**
     * Whether this alert route is enabled or not
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    declare public readonly escalationConfig: pulumi.Output<outputs.AlertRouteEscalationConfig>;
    /**
     * The expressions to be prepared for use by steps and conditions
     */
    declare public readonly expressions: pulumi.Output<outputs.AlertRouteExpression[]>;
    declare public readonly incidentConfig: pulumi.Output<outputs.AlertRouteIncidentConfig>;
    declare public readonly incidentTemplate: pulumi.Output<outputs.AlertRouteIncidentTemplate>;
    /**
     * Whether this alert route is private. Private alert routes will only create private incidents from alerts.
     */
    declare public readonly isPrivate: pulumi.Output<boolean>;
    declare public readonly messageTemplate: pulumi.Output<outputs.AlertRouteMessageTemplate | undefined>;
    /**
     * The name of this alert route config, for the user's reference
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * IDs of teams that own this alert route
     */
    declare public readonly owningTeamIds: pulumi.Output<string[] | undefined>;

    /**
     * Create a AlertRoute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertRouteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertRouteArgs | AlertRouteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertRouteState | undefined;
            resourceInputs["alertSources"] = state?.alertSources;
            resourceInputs["channelConfigs"] = state?.channelConfigs;
            resourceInputs["conditionGroups"] = state?.conditionGroups;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["escalationConfig"] = state?.escalationConfig;
            resourceInputs["expressions"] = state?.expressions;
            resourceInputs["incidentConfig"] = state?.incidentConfig;
            resourceInputs["incidentTemplate"] = state?.incidentTemplate;
            resourceInputs["isPrivate"] = state?.isPrivate;
            resourceInputs["messageTemplate"] = state?.messageTemplate;
            resourceInputs["name"] = state?.name;
            resourceInputs["owningTeamIds"] = state?.owningTeamIds;
        } else {
            const args = argsOrState as AlertRouteArgs | undefined;
            if (args?.alertSources === undefined && !opts.urn) {
                throw new Error("Missing required property 'alertSources'");
            }
            if (args?.conditionGroups === undefined && !opts.urn) {
                throw new Error("Missing required property 'conditionGroups'");
            }
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.escalationConfig === undefined && !opts.urn) {
                throw new Error("Missing required property 'escalationConfig'");
            }
            if (args?.expressions === undefined && !opts.urn) {
                throw new Error("Missing required property 'expressions'");
            }
            if (args?.incidentConfig === undefined && !opts.urn) {
                throw new Error("Missing required property 'incidentConfig'");
            }
            if (args?.incidentTemplate === undefined && !opts.urn) {
                throw new Error("Missing required property 'incidentTemplate'");
            }
            if (args?.isPrivate === undefined && !opts.urn) {
                throw new Error("Missing required property 'isPrivate'");
            }
            resourceInputs["alertSources"] = args?.alertSources;
            resourceInputs["channelConfigs"] = args?.channelConfigs;
            resourceInputs["conditionGroups"] = args?.conditionGroups;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["escalationConfig"] = args?.escalationConfig;
            resourceInputs["expressions"] = args?.expressions;
            resourceInputs["incidentConfig"] = args?.incidentConfig;
            resourceInputs["incidentTemplate"] = args?.incidentTemplate;
            resourceInputs["isPrivate"] = args?.isPrivate;
            resourceInputs["messageTemplate"] = args?.messageTemplate;
            resourceInputs["name"] = args?.name;
            resourceInputs["owningTeamIds"] = args?.owningTeamIds;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AlertRoute.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AlertRoute resources.
 */
export interface AlertRouteState {
    /**
     * Which alert sources should this alert route match?
     */
    alertSources?: pulumi.Input<pulumi.Input<inputs.AlertRouteAlertSource>[]>;
    /**
     * The channel configuration for this alert route
     */
    channelConfigs?: pulumi.Input<pulumi.Input<inputs.AlertRouteChannelConfig>[]>;
    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    conditionGroups?: pulumi.Input<pulumi.Input<inputs.AlertRouteConditionGroup>[]>;
    /**
     * Whether this alert route is enabled or not
     */
    enabled?: pulumi.Input<boolean>;
    escalationConfig?: pulumi.Input<inputs.AlertRouteEscalationConfig>;
    /**
     * The expressions to be prepared for use by steps and conditions
     */
    expressions?: pulumi.Input<pulumi.Input<inputs.AlertRouteExpression>[]>;
    incidentConfig?: pulumi.Input<inputs.AlertRouteIncidentConfig>;
    incidentTemplate?: pulumi.Input<inputs.AlertRouteIncidentTemplate>;
    /**
     * Whether this alert route is private. Private alert routes will only create private incidents from alerts.
     */
    isPrivate?: pulumi.Input<boolean>;
    messageTemplate?: pulumi.Input<inputs.AlertRouteMessageTemplate>;
    /**
     * The name of this alert route config, for the user's reference
     */
    name?: pulumi.Input<string>;
    /**
     * IDs of teams that own this alert route
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a AlertRoute resource.
 */
export interface AlertRouteArgs {
    /**
     * Which alert sources should this alert route match?
     */
    alertSources: pulumi.Input<pulumi.Input<inputs.AlertRouteAlertSource>[]>;
    /**
     * The channel configuration for this alert route
     */
    channelConfigs?: pulumi.Input<pulumi.Input<inputs.AlertRouteChannelConfig>[]>;
    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    conditionGroups: pulumi.Input<pulumi.Input<inputs.AlertRouteConditionGroup>[]>;
    /**
     * Whether this alert route is enabled or not
     */
    enabled: pulumi.Input<boolean>;
    escalationConfig: pulumi.Input<inputs.AlertRouteEscalationConfig>;
    /**
     * The expressions to be prepared for use by steps and conditions
     */
    expressions: pulumi.Input<pulumi.Input<inputs.AlertRouteExpression>[]>;
    incidentConfig: pulumi.Input<inputs.AlertRouteIncidentConfig>;
    incidentTemplate: pulumi.Input<inputs.AlertRouteIncidentTemplate>;
    /**
     * Whether this alert route is private. Private alert routes will only create private incidents from alerts.
     */
    isPrivate: pulumi.Input<boolean>;
    messageTemplate?: pulumi.Input<inputs.AlertRouteMessageTemplate>;
    /**
     * The name of this alert route config, for the user's reference
     */
    name?: pulumi.Input<string>;
    /**
     * IDs of teams that own this alert route
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[]>;
}
