// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AlertSource extends pulumi.CustomResource {
    /**
     * Get an existing AlertSource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertSourceState, opts?: pulumi.CustomResourceOptions): AlertSource {
        return new AlertSource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/alertSource:AlertSource';

    /**
     * Returns true if the given object is an instance of AlertSource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlertSource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlertSource.__pulumiType;
    }

    /**
     * Whether to auto-resolve incident alerts when the alert auto-resolves. Defaults to true.
     */
    declare public readonly autoResolveIncidentAlerts: pulumi.Output<boolean>;
    /**
     * When set, alerts from this source will automatically resolve after this many minutes.
     */
    declare public readonly autoResolveTimeoutMinutes: pulumi.Output<number | undefined>;
    /**
     * Email address this alert source receives alerts to
     */
    declare public readonly emailAddress: pulumi.Output<string>;
    declare public readonly httpCustomOptions: pulumi.Output<outputs.AlertSourceHttpCustomOptions | undefined>;
    declare public readonly jiraOptions: pulumi.Output<outputs.AlertSourceJiraOptions | undefined>;
    /**
     * Unique name of the alert source
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * IDs of teams that own this alert source
     */
    declare public readonly owningTeamIds: pulumi.Output<string[] | undefined>;
    /**
     * Secret token used to authenticate this source, if applicable. If applicable, this is the token that must be included in either the query string or the 'Authorization' header when sending events to this alert source.
     */
    declare public /*out*/ readonly secretToken: pulumi.Output<string>;
    /**
     * Type of alert source
     */
    declare public readonly sourceType: pulumi.Output<string>;
    declare public readonly template: pulumi.Output<outputs.AlertSourceTemplate>;

    /**
     * Create a AlertSource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertSourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertSourceArgs | AlertSourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertSourceState | undefined;
            resourceInputs["autoResolveIncidentAlerts"] = state?.autoResolveIncidentAlerts;
            resourceInputs["autoResolveTimeoutMinutes"] = state?.autoResolveTimeoutMinutes;
            resourceInputs["emailAddress"] = state?.emailAddress;
            resourceInputs["httpCustomOptions"] = state?.httpCustomOptions;
            resourceInputs["jiraOptions"] = state?.jiraOptions;
            resourceInputs["name"] = state?.name;
            resourceInputs["owningTeamIds"] = state?.owningTeamIds;
            resourceInputs["secretToken"] = state?.secretToken;
            resourceInputs["sourceType"] = state?.sourceType;
            resourceInputs["template"] = state?.template;
        } else {
            const args = argsOrState as AlertSourceArgs | undefined;
            if (args?.sourceType === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceType'");
            }
            if (args?.template === undefined && !opts.urn) {
                throw new Error("Missing required property 'template'");
            }
            resourceInputs["autoResolveIncidentAlerts"] = args?.autoResolveIncidentAlerts;
            resourceInputs["autoResolveTimeoutMinutes"] = args?.autoResolveTimeoutMinutes;
            resourceInputs["emailAddress"] = args?.emailAddress;
            resourceInputs["httpCustomOptions"] = args?.httpCustomOptions;
            resourceInputs["jiraOptions"] = args?.jiraOptions;
            resourceInputs["name"] = args?.name;
            resourceInputs["owningTeamIds"] = args?.owningTeamIds;
            resourceInputs["sourceType"] = args?.sourceType;
            resourceInputs["template"] = args?.template;
            resourceInputs["secretToken"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AlertSource.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AlertSource resources.
 */
export interface AlertSourceState {
    /**
     * Whether to auto-resolve incident alerts when the alert auto-resolves. Defaults to true.
     */
    autoResolveIncidentAlerts?: pulumi.Input<boolean>;
    /**
     * When set, alerts from this source will automatically resolve after this many minutes.
     */
    autoResolveTimeoutMinutes?: pulumi.Input<number>;
    /**
     * Email address this alert source receives alerts to
     */
    emailAddress?: pulumi.Input<string>;
    httpCustomOptions?: pulumi.Input<inputs.AlertSourceHttpCustomOptions>;
    jiraOptions?: pulumi.Input<inputs.AlertSourceJiraOptions>;
    /**
     * Unique name of the alert source
     */
    name?: pulumi.Input<string>;
    /**
     * IDs of teams that own this alert source
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Secret token used to authenticate this source, if applicable. If applicable, this is the token that must be included in either the query string or the 'Authorization' header when sending events to this alert source.
     */
    secretToken?: pulumi.Input<string>;
    /**
     * Type of alert source
     */
    sourceType?: pulumi.Input<string>;
    template?: pulumi.Input<inputs.AlertSourceTemplate>;
}

/**
 * The set of arguments for constructing a AlertSource resource.
 */
export interface AlertSourceArgs {
    /**
     * Whether to auto-resolve incident alerts when the alert auto-resolves. Defaults to true.
     */
    autoResolveIncidentAlerts?: pulumi.Input<boolean>;
    /**
     * When set, alerts from this source will automatically resolve after this many minutes.
     */
    autoResolveTimeoutMinutes?: pulumi.Input<number>;
    /**
     * Email address this alert source receives alerts to
     */
    emailAddress?: pulumi.Input<string>;
    httpCustomOptions?: pulumi.Input<inputs.AlertSourceHttpCustomOptions>;
    jiraOptions?: pulumi.Input<inputs.AlertSourceJiraOptions>;
    /**
     * Unique name of the alert source
     */
    name?: pulumi.Input<string>;
    /**
     * IDs of teams that own this alert source
     */
    owningTeamIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Type of alert source
     */
    sourceType: pulumi.Input<string>;
    template: pulumi.Input<inputs.AlertSourceTemplate>;
}
