// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CatalogEntries extends pulumi.CustomResource {
    /**
     * Get an existing CatalogEntries resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CatalogEntriesState, opts?: pulumi.CustomResourceOptions): CatalogEntries {
        return new CatalogEntries(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/catalogEntries:CatalogEntries';

    /**
     * Returns true if the given object is an instance of CatalogEntries.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CatalogEntries {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CatalogEntries.__pulumiType;
    }

    /**
     * ID of this catalog type
     */
    declare public readonly catalogEntriesId: pulumi.Output<string>;
    /**
     * Map of external ID to entry in the catalog.
     */
    declare public readonly entries: pulumi.Output<{[key: string]: outputs.CatalogEntriesEntries}>;
    /**
     * The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.
     *
     * This can be used to allow other attributes of a catalog entry to be managed elsewhere, for example in another Terraform repository or the incident.io web UI.
     */
    declare public readonly managedAttributes: pulumi.Output<string[] | undefined>;

    /**
     * Create a CatalogEntries resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CatalogEntriesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CatalogEntriesArgs | CatalogEntriesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CatalogEntriesState | undefined;
            resourceInputs["catalogEntriesId"] = state?.catalogEntriesId;
            resourceInputs["entries"] = state?.entries;
            resourceInputs["managedAttributes"] = state?.managedAttributes;
        } else {
            const args = argsOrState as CatalogEntriesArgs | undefined;
            if (args?.catalogEntriesId === undefined && !opts.urn) {
                throw new Error("Missing required property 'catalogEntriesId'");
            }
            if (args?.entries === undefined && !opts.urn) {
                throw new Error("Missing required property 'entries'");
            }
            resourceInputs["catalogEntriesId"] = args?.catalogEntriesId;
            resourceInputs["entries"] = args?.entries;
            resourceInputs["managedAttributes"] = args?.managedAttributes;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CatalogEntries.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CatalogEntries resources.
 */
export interface CatalogEntriesState {
    /**
     * ID of this catalog type
     */
    catalogEntriesId?: pulumi.Input<string>;
    /**
     * Map of external ID to entry in the catalog.
     */
    entries?: pulumi.Input<{[key: string]: pulumi.Input<inputs.CatalogEntriesEntries>}>;
    /**
     * The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.
     *
     * This can be used to allow other attributes of a catalog entry to be managed elsewhere, for example in another Terraform repository or the incident.io web UI.
     */
    managedAttributes?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a CatalogEntries resource.
 */
export interface CatalogEntriesArgs {
    /**
     * ID of this catalog type
     */
    catalogEntriesId: pulumi.Input<string>;
    /**
     * Map of external ID to entry in the catalog.
     */
    entries: pulumi.Input<{[key: string]: pulumi.Input<inputs.CatalogEntriesEntries>}>;
    /**
     * The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.
     *
     * This can be used to allow other attributes of a catalog entry to be managed elsewhere, for example in another Terraform repository or the incident.io web UI.
     */
    managedAttributes?: pulumi.Input<pulumi.Input<string>[]>;
}
