// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CatalogType extends pulumi.CustomResource {
    /**
     * Get an existing CatalogType resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CatalogTypeState, opts?: pulumi.CustomResourceOptions): CatalogType {
        return new CatalogType(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/catalogType:CatalogType';

    /**
     * Returns true if the given object is an instance of CatalogType.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CatalogType {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CatalogType.__pulumiType;
    }

    /**
     * The categories that this type belongs to, to be shown in the web dashboard. Possible values are: <span pulumi-lang-nodejs="`customer`" pulumi-lang-dotnet="`Customer`" pulumi-lang-go="`customer`" pulumi-lang-python="`customer`" pulumi-lang-yaml="`customer`" pulumi-lang-java="`customer`">`customer`</span>, `issue-tracker`, `product-feature`, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`">`service`</span>, `on-call`, <span pulumi-lang-nodejs="`team`" pulumi-lang-dotnet="`Team`" pulumi-lang-go="`team`" pulumi-lang-python="`team`" pulumi-lang-yaml="`team`" pulumi-lang-java="`team`">`team`</span>, <span pulumi-lang-nodejs="`user`" pulumi-lang-dotnet="`User`" pulumi-lang-go="`user`" pulumi-lang-python="`user`" pulumi-lang-yaml="`user`" pulumi-lang-java="`user`">`user`</span>.
     */
    declare public readonly categories: pulumi.Output<string[]>;
    /**
     * Human readble description of this type
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Name is the human readable name of this type
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The url of the external repository where this type is managed. Users will not be able to edit the catalog type (or its entries) via the UI, and will instead be provided a link to this URL.
     */
    declare public readonly sourceRepoUrl: pulumi.Output<string>;
    /**
     * The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
     */
    declare public readonly typeName: pulumi.Output<string>;
    /**
     * If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
     */
    declare public readonly useNameAsIdentifier: pulumi.Output<boolean>;

    /**
     * Create a CatalogType resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CatalogTypeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CatalogTypeArgs | CatalogTypeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CatalogTypeState | undefined;
            resourceInputs["categories"] = state?.categories;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["sourceRepoUrl"] = state?.sourceRepoUrl;
            resourceInputs["typeName"] = state?.typeName;
            resourceInputs["useNameAsIdentifier"] = state?.useNameAsIdentifier;
        } else {
            const args = argsOrState as CatalogTypeArgs | undefined;
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.sourceRepoUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceRepoUrl'");
            }
            resourceInputs["categories"] = args?.categories;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["sourceRepoUrl"] = args?.sourceRepoUrl;
            resourceInputs["typeName"] = args?.typeName;
            resourceInputs["useNameAsIdentifier"] = args?.useNameAsIdentifier;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CatalogType.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CatalogType resources.
 */
export interface CatalogTypeState {
    /**
     * The categories that this type belongs to, to be shown in the web dashboard. Possible values are: <span pulumi-lang-nodejs="`customer`" pulumi-lang-dotnet="`Customer`" pulumi-lang-go="`customer`" pulumi-lang-python="`customer`" pulumi-lang-yaml="`customer`" pulumi-lang-java="`customer`">`customer`</span>, `issue-tracker`, `product-feature`, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`">`service`</span>, `on-call`, <span pulumi-lang-nodejs="`team`" pulumi-lang-dotnet="`Team`" pulumi-lang-go="`team`" pulumi-lang-python="`team`" pulumi-lang-yaml="`team`" pulumi-lang-java="`team`">`team`</span>, <span pulumi-lang-nodejs="`user`" pulumi-lang-dotnet="`User`" pulumi-lang-go="`user`" pulumi-lang-python="`user`" pulumi-lang-yaml="`user`" pulumi-lang-java="`user`">`user`</span>.
     */
    categories?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Human readble description of this type
     */
    description?: pulumi.Input<string>;
    /**
     * Name is the human readable name of this type
     */
    name?: pulumi.Input<string>;
    /**
     * The url of the external repository where this type is managed. Users will not be able to edit the catalog type (or its entries) via the UI, and will instead be provided a link to this URL.
     */
    sourceRepoUrl?: pulumi.Input<string>;
    /**
     * The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
     */
    typeName?: pulumi.Input<string>;
    /**
     * If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
     */
    useNameAsIdentifier?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a CatalogType resource.
 */
export interface CatalogTypeArgs {
    /**
     * The categories that this type belongs to, to be shown in the web dashboard. Possible values are: <span pulumi-lang-nodejs="`customer`" pulumi-lang-dotnet="`Customer`" pulumi-lang-go="`customer`" pulumi-lang-python="`customer`" pulumi-lang-yaml="`customer`" pulumi-lang-java="`customer`">`customer`</span>, `issue-tracker`, `product-feature`, <span pulumi-lang-nodejs="`service`" pulumi-lang-dotnet="`Service`" pulumi-lang-go="`service`" pulumi-lang-python="`service`" pulumi-lang-yaml="`service`" pulumi-lang-java="`service`">`service`</span>, `on-call`, <span pulumi-lang-nodejs="`team`" pulumi-lang-dotnet="`Team`" pulumi-lang-go="`team`" pulumi-lang-python="`team`" pulumi-lang-yaml="`team`" pulumi-lang-java="`team`">`team`</span>, <span pulumi-lang-nodejs="`user`" pulumi-lang-dotnet="`User`" pulumi-lang-go="`user`" pulumi-lang-python="`user`" pulumi-lang-yaml="`user`" pulumi-lang-java="`user`">`user`</span>.
     */
    categories?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Human readble description of this type
     */
    description: pulumi.Input<string>;
    /**
     * Name is the human readable name of this type
     */
    name?: pulumi.Input<string>;
    /**
     * The url of the external repository where this type is managed. Users will not be able to edit the catalog type (or its entries) via the UI, and will instead be provided a link to this URL.
     */
    sourceRepoUrl: pulumi.Input<string>;
    /**
     * The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
     */
    typeName?: pulumi.Input<string>;
    /**
     * If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
     */
    useNameAsIdentifier?: pulumi.Input<boolean>;
}
