// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CustomField extends pulumi.CustomResource {
    /**
     * Get an existing CustomField resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomFieldState, opts?: pulumi.CustomResourceOptions): CustomField {
        return new CustomField(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/customField:CustomField';

    /**
     * Returns true if the given object is an instance of CustomField.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomField {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomField.__pulumiType;
    }

    /**
     * For catalog fields, the ID of the associated catalog type
     */
    declare public readonly catalogTypeId: pulumi.Output<string | undefined>;
    /**
     * Description of the custom field
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Type of custom field. Possible values are: <span pulumi-lang-nodejs="`singleSelect`" pulumi-lang-dotnet="`SingleSelect`" pulumi-lang-go="`singleSelect`" pulumi-lang-python="`single_select`" pulumi-lang-yaml="`singleSelect`" pulumi-lang-java="`singleSelect`">`single_select`</span>, <span pulumi-lang-nodejs="`multiSelect`" pulumi-lang-dotnet="`MultiSelect`" pulumi-lang-go="`multiSelect`" pulumi-lang-python="`multi_select`" pulumi-lang-yaml="`multiSelect`" pulumi-lang-java="`multiSelect`">`multi_select`</span>, <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span>, <span pulumi-lang-nodejs="`link`" pulumi-lang-dotnet="`Link`" pulumi-lang-go="`link`" pulumi-lang-python="`link`" pulumi-lang-yaml="`link`" pulumi-lang-java="`link`">`link`</span>, <span pulumi-lang-nodejs="`numeric`" pulumi-lang-dotnet="`Numeric`" pulumi-lang-go="`numeric`" pulumi-lang-python="`numeric`" pulumi-lang-yaml="`numeric`" pulumi-lang-java="`numeric`">`numeric`</span>.
     */
    declare public readonly fieldType: pulumi.Output<string>;
    declare public readonly filterBy: pulumi.Output<outputs.CustomFieldFilterBy | undefined>;
    /**
     * For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
     */
    declare public readonly groupByCatalogAttributeId: pulumi.Output<string | undefined>;
    /**
     * Which catalog attribute provides helptext for the options
     */
    declare public readonly helptextCatalogAttributeId: pulumi.Output<string | undefined>;
    /**
     * Human readable name for the custom field
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a CustomField resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomFieldArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomFieldArgs | CustomFieldState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomFieldState | undefined;
            resourceInputs["catalogTypeId"] = state?.catalogTypeId;
            resourceInputs["description"] = state?.description;
            resourceInputs["fieldType"] = state?.fieldType;
            resourceInputs["filterBy"] = state?.filterBy;
            resourceInputs["groupByCatalogAttributeId"] = state?.groupByCatalogAttributeId;
            resourceInputs["helptextCatalogAttributeId"] = state?.helptextCatalogAttributeId;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as CustomFieldArgs | undefined;
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.fieldType === undefined && !opts.urn) {
                throw new Error("Missing required property 'fieldType'");
            }
            resourceInputs["catalogTypeId"] = args?.catalogTypeId;
            resourceInputs["description"] = args?.description;
            resourceInputs["fieldType"] = args?.fieldType;
            resourceInputs["filterBy"] = args?.filterBy;
            resourceInputs["groupByCatalogAttributeId"] = args?.groupByCatalogAttributeId;
            resourceInputs["helptextCatalogAttributeId"] = args?.helptextCatalogAttributeId;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomField.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CustomField resources.
 */
export interface CustomFieldState {
    /**
     * For catalog fields, the ID of the associated catalog type
     */
    catalogTypeId?: pulumi.Input<string>;
    /**
     * Description of the custom field
     */
    description?: pulumi.Input<string>;
    /**
     * Type of custom field. Possible values are: <span pulumi-lang-nodejs="`singleSelect`" pulumi-lang-dotnet="`SingleSelect`" pulumi-lang-go="`singleSelect`" pulumi-lang-python="`single_select`" pulumi-lang-yaml="`singleSelect`" pulumi-lang-java="`singleSelect`">`single_select`</span>, <span pulumi-lang-nodejs="`multiSelect`" pulumi-lang-dotnet="`MultiSelect`" pulumi-lang-go="`multiSelect`" pulumi-lang-python="`multi_select`" pulumi-lang-yaml="`multiSelect`" pulumi-lang-java="`multiSelect`">`multi_select`</span>, <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span>, <span pulumi-lang-nodejs="`link`" pulumi-lang-dotnet="`Link`" pulumi-lang-go="`link`" pulumi-lang-python="`link`" pulumi-lang-yaml="`link`" pulumi-lang-java="`link`">`link`</span>, <span pulumi-lang-nodejs="`numeric`" pulumi-lang-dotnet="`Numeric`" pulumi-lang-go="`numeric`" pulumi-lang-python="`numeric`" pulumi-lang-yaml="`numeric`" pulumi-lang-java="`numeric`">`numeric`</span>.
     */
    fieldType?: pulumi.Input<string>;
    filterBy?: pulumi.Input<inputs.CustomFieldFilterBy>;
    /**
     * For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
     */
    groupByCatalogAttributeId?: pulumi.Input<string>;
    /**
     * Which catalog attribute provides helptext for the options
     */
    helptextCatalogAttributeId?: pulumi.Input<string>;
    /**
     * Human readable name for the custom field
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CustomField resource.
 */
export interface CustomFieldArgs {
    /**
     * For catalog fields, the ID of the associated catalog type
     */
    catalogTypeId?: pulumi.Input<string>;
    /**
     * Description of the custom field
     */
    description: pulumi.Input<string>;
    /**
     * Type of custom field. Possible values are: <span pulumi-lang-nodejs="`singleSelect`" pulumi-lang-dotnet="`SingleSelect`" pulumi-lang-go="`singleSelect`" pulumi-lang-python="`single_select`" pulumi-lang-yaml="`singleSelect`" pulumi-lang-java="`singleSelect`">`single_select`</span>, <span pulumi-lang-nodejs="`multiSelect`" pulumi-lang-dotnet="`MultiSelect`" pulumi-lang-go="`multiSelect`" pulumi-lang-python="`multi_select`" pulumi-lang-yaml="`multiSelect`" pulumi-lang-java="`multiSelect`">`multi_select`</span>, <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span>, <span pulumi-lang-nodejs="`link`" pulumi-lang-dotnet="`Link`" pulumi-lang-go="`link`" pulumi-lang-python="`link`" pulumi-lang-yaml="`link`" pulumi-lang-java="`link`">`link`</span>, <span pulumi-lang-nodejs="`numeric`" pulumi-lang-dotnet="`Numeric`" pulumi-lang-go="`numeric`" pulumi-lang-python="`numeric`" pulumi-lang-yaml="`numeric`" pulumi-lang-java="`numeric`">`numeric`</span>.
     */
    fieldType: pulumi.Input<string>;
    filterBy?: pulumi.Input<inputs.CustomFieldFilterBy>;
    /**
     * For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
     */
    groupByCatalogAttributeId?: pulumi.Input<string>;
    /**
     * Which catalog attribute provides helptext for the options
     */
    helptextCatalogAttributeId?: pulumi.Input<string>;
    /**
     * Human readable name for the custom field
     */
    name?: pulumi.Input<string>;
}
