// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class EscalationPath extends pulumi.CustomResource {
    /**
     * Get an existing EscalationPath resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EscalationPathState, opts?: pulumi.CustomResourceOptions): EscalationPath {
        return new EscalationPath(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/escalationPath:EscalationPath';

    /**
     * Returns true if the given object is an instance of EscalationPath.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EscalationPath {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EscalationPath.__pulumiType;
    }

    /**
     * The name of this escalation path, for the user's reference.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The nodes that form the levels and branches of this escalation path.
     *
     * -->**Note** Although the <span pulumi-lang-nodejs="`ifElse`" pulumi-lang-dotnet="`IfElse`" pulumi-lang-go="`ifElse`" pulumi-lang-python="`if_else`" pulumi-lang-yaml="`ifElse`" pulumi-lang-java="`ifElse`">`if_else`</span> block is recursive, currently a maximum of 3 levels are supported. Attempting to configure more than 3 levels of nesting will result in a schema error.
     */
    declare public readonly paths: pulumi.Output<outputs.EscalationPathPath[]>;
    /**
     * IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
     */
    declare public readonly teamIds: pulumi.Output<string[] | undefined>;
    /**
     * The working hours for this escalation path.
     */
    declare public readonly workingHours: pulumi.Output<outputs.EscalationPathWorkingHour[] | undefined>;

    /**
     * Create a EscalationPath resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EscalationPathArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EscalationPathArgs | EscalationPathState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EscalationPathState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["paths"] = state?.paths;
            resourceInputs["teamIds"] = state?.teamIds;
            resourceInputs["workingHours"] = state?.workingHours;
        } else {
            const args = argsOrState as EscalationPathArgs | undefined;
            if (args?.paths === undefined && !opts.urn) {
                throw new Error("Missing required property 'paths'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["paths"] = args?.paths;
            resourceInputs["teamIds"] = args?.teamIds;
            resourceInputs["workingHours"] = args?.workingHours;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EscalationPath.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EscalationPath resources.
 */
export interface EscalationPathState {
    /**
     * The name of this escalation path, for the user's reference.
     */
    name?: pulumi.Input<string>;
    /**
     * The nodes that form the levels and branches of this escalation path.
     *
     * -->**Note** Although the <span pulumi-lang-nodejs="`ifElse`" pulumi-lang-dotnet="`IfElse`" pulumi-lang-go="`ifElse`" pulumi-lang-python="`if_else`" pulumi-lang-yaml="`ifElse`" pulumi-lang-java="`ifElse`">`if_else`</span> block is recursive, currently a maximum of 3 levels are supported. Attempting to configure more than 3 levels of nesting will result in a schema error.
     */
    paths?: pulumi.Input<pulumi.Input<inputs.EscalationPathPath>[]>;
    /**
     * IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
     */
    teamIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The working hours for this escalation path.
     */
    workingHours?: pulumi.Input<pulumi.Input<inputs.EscalationPathWorkingHour>[]>;
}

/**
 * The set of arguments for constructing a EscalationPath resource.
 */
export interface EscalationPathArgs {
    /**
     * The name of this escalation path, for the user's reference.
     */
    name?: pulumi.Input<string>;
    /**
     * The nodes that form the levels and branches of this escalation path.
     *
     * -->**Note** Although the <span pulumi-lang-nodejs="`ifElse`" pulumi-lang-dotnet="`IfElse`" pulumi-lang-go="`ifElse`" pulumi-lang-python="`if_else`" pulumi-lang-yaml="`ifElse`" pulumi-lang-java="`ifElse`">`if_else`</span> block is recursive, currently a maximum of 3 levels are supported. Attempting to configure more than 3 levels of nesting will result in a schema error.
     */
    paths: pulumi.Input<pulumi.Input<inputs.EscalationPathPath>[]>;
    /**
     * IDs of the teams that own this escalation path. This will automatically sync escalation paths with the right teams in Catalog. If you have an escalation paths attribute on your Teams, this attribute is required.
     */
    teamIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The working hours for this escalation path.
     */
    workingHours?: pulumi.Input<pulumi.Input<inputs.EscalationPathWorkingHour>[]>;
}
