// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAlertAttribute(args: GetAlertAttributeArgs, opts?: pulumi.InvokeOptions): Promise<GetAlertAttributeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getAlertAttribute:getAlertAttribute", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAlertAttribute.
 */
export interface GetAlertAttributeArgs {
    name: string;
}

/**
 * A collection of values returned by getAlertAttribute.
 */
export interface GetAlertAttributeResult {
    readonly array: boolean;
    readonly emoji: string;
    readonly id: string;
    readonly name: string;
    readonly required: boolean;
    readonly type: string;
}
export function getAlertAttributeOutput(args: GetAlertAttributeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAlertAttributeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getAlertAttribute:getAlertAttribute", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAlertAttribute.
 */
export interface GetAlertAttributeOutputArgs {
    name: pulumi.Input<string>;
}
