// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAlertSources(args?: GetAlertSourcesArgs, opts?: pulumi.InvokeOptions): Promise<GetAlertSourcesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getAlertSources:getAlertSources", {
        "sourceType": args.sourceType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAlertSources.
 */
export interface GetAlertSourcesArgs {
    sourceType?: string;
}

/**
 * A collection of values returned by getAlertSources.
 */
export interface GetAlertSourcesResult {
    readonly alertSources: outputs.GetAlertSourcesAlertSource[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly sourceType?: string;
}
export function getAlertSourcesOutput(args?: GetAlertSourcesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAlertSourcesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getAlertSources:getAlertSources", {
        "sourceType": args.sourceType,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAlertSources.
 */
export interface GetAlertSourcesOutputArgs {
    sourceType?: pulumi.Input<string>;
}
