// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCatalogEntry(args: GetCatalogEntryArgs, opts?: pulumi.InvokeOptions): Promise<GetCatalogEntryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getCatalogEntry:getCatalogEntry", {
        "catalogTypeId": args.catalogTypeId,
        "identifier": args.identifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCatalogEntry.
 */
export interface GetCatalogEntryArgs {
    catalogTypeId: string;
    identifier: string;
}

/**
 * A collection of values returned by getCatalogEntry.
 */
export interface GetCatalogEntryResult {
    readonly aliases: string[];
    readonly attributeValues: outputs.GetCatalogEntryAttributeValue[];
    readonly catalogTypeId: string;
    readonly externalId: string;
    readonly id: string;
    readonly identifier: string;
    readonly name: string;
    readonly rank: number;
}
export function getCatalogEntryOutput(args: GetCatalogEntryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCatalogEntryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getCatalogEntry:getCatalogEntry", {
        "catalogTypeId": args.catalogTypeId,
        "identifier": args.identifier,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCatalogEntry.
 */
export interface GetCatalogEntryOutputArgs {
    catalogTypeId: pulumi.Input<string>;
    identifier: pulumi.Input<string>;
}
