// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCustomField(args: GetCustomFieldArgs, opts?: pulumi.InvokeOptions): Promise<GetCustomFieldResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getCustomField:getCustomField", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCustomField.
 */
export interface GetCustomFieldArgs {
    name: string;
}

/**
 * A collection of values returned by getCustomField.
 */
export interface GetCustomFieldResult {
    readonly catalogTypeId: string;
    readonly description: string;
    readonly fieldType: string;
    readonly filterBy: outputs.GetCustomFieldFilterBy;
    readonly groupByCatalogAttributeId: string;
    readonly helptextCatalogAttributeId: string;
    readonly id: string;
    readonly name: string;
}
export function getCustomFieldOutput(args: GetCustomFieldOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCustomFieldResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getCustomField:getCustomField", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCustomField.
 */
export interface GetCustomFieldOutputArgs {
    name: pulumi.Input<string>;
}
