// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCatalogTypeAttribute(args: GetCatalogTypeAttributeArgs, opts?: pulumi.InvokeOptions): Promise<GetCatalogTypeAttributeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getCatalogTypeAttribute:getCatalogTypeAttribute", {
        "catalogTypeId": args.catalogTypeId,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCatalogTypeAttribute.
 */
export interface GetCatalogTypeAttributeArgs {
    catalogTypeId: string;
    name: string;
}

/**
 * A collection of values returned by getCatalogTypeAttribute.
 */
export interface GetCatalogTypeAttributeResult {
    readonly array: boolean;
    readonly backlinkAttribute: string;
    readonly catalogTypeId: string;
    readonly id: string;
    readonly name: string;
    readonly paths: string[];
    readonly schemaOnly: boolean;
    readonly type: string;
}
export function getCatalogTypeAttributeOutput(args: GetCatalogTypeAttributeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCatalogTypeAttributeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getCatalogTypeAttribute:getCatalogTypeAttribute", {
        "catalogTypeId": args.catalogTypeId,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCatalogTypeAttribute.
 */
export interface GetCatalogTypeAttributeOutputArgs {
    catalogTypeId: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
