// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCatalogEntries(args: GetCatalogEntriesArgs, opts?: pulumi.InvokeOptions): Promise<GetCatalogEntriesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getCatalogEntries:getCatalogEntries", {
        "catalogTypeId": args.catalogTypeId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCatalogEntries.
 */
export interface GetCatalogEntriesArgs {
    catalogTypeId: string;
}

/**
 * A collection of values returned by getCatalogEntries.
 */
export interface GetCatalogEntriesResult {
    readonly catalogEntries: outputs.GetCatalogEntriesCatalogEntry[];
    readonly catalogTypeId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getCatalogEntriesOutput(args: GetCatalogEntriesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCatalogEntriesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getCatalogEntries:getCatalogEntries", {
        "catalogTypeId": args.catalogTypeId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCatalogEntries.
 */
export interface GetCatalogEntriesOutputArgs {
    catalogTypeId: pulumi.Input<string>;
}
