// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getEscalationPath(args?: GetEscalationPathArgs, opts?: pulumi.InvokeOptions): Promise<GetEscalationPathResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getEscalationPath:getEscalationPath", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEscalationPath.
 */
export interface GetEscalationPathArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getEscalationPath.
 */
export interface GetEscalationPathResult {
    readonly id: string;
    readonly name: string;
    readonly paths: outputs.GetEscalationPathPath[];
    readonly teamIds: string[];
    readonly workingHours: outputs.GetEscalationPathWorkingHour[];
}
export function getEscalationPathOutput(args?: GetEscalationPathOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEscalationPathResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getEscalationPath:getEscalationPath", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEscalationPath.
 */
export interface GetEscalationPathOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
