// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIncidentTypes(opts?: pulumi.InvokeOptions): Promise<GetIncidentTypesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("incident:index/getIncidentTypes:getIncidentTypes", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getIncidentTypes.
 */
export interface GetIncidentTypesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly incidentTypes: outputs.GetIncidentTypesIncidentType[];
}
export function getIncidentTypesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIncidentTypesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("incident:index/getIncidentTypes:getIncidentTypes", {
    }, opts, utilities.getPackage());
}
