// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Schedule extends pulumi.CustomResource {
    /**
     * Get an existing Schedule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ScheduleState, opts?: pulumi.CustomResourceOptions): Schedule {
        return new Schedule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/schedule:Schedule';

    /**
     * Returns true if the given object is an instance of Schedule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Schedule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Schedule.__pulumiType;
    }

    declare public readonly holidaysPublicConfig: pulumi.Output<outputs.ScheduleHolidaysPublicConfig | undefined>;
    /**
     * Human readable name synced from external provider
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly rotations: pulumi.Output<outputs.ScheduleRotation[]>;
    /**
     * IDs of teams that own this schedule
     */
    declare public readonly teamIds: pulumi.Output<string[] | undefined>;
    declare public readonly timezone: pulumi.Output<string>;

    /**
     * Create a Schedule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ScheduleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ScheduleArgs | ScheduleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ScheduleState | undefined;
            resourceInputs["holidaysPublicConfig"] = state?.holidaysPublicConfig;
            resourceInputs["name"] = state?.name;
            resourceInputs["rotations"] = state?.rotations;
            resourceInputs["teamIds"] = state?.teamIds;
            resourceInputs["timezone"] = state?.timezone;
        } else {
            const args = argsOrState as ScheduleArgs | undefined;
            if (args?.rotations === undefined && !opts.urn) {
                throw new Error("Missing required property 'rotations'");
            }
            if (args?.timezone === undefined && !opts.urn) {
                throw new Error("Missing required property 'timezone'");
            }
            resourceInputs["holidaysPublicConfig"] = args?.holidaysPublicConfig;
            resourceInputs["name"] = args?.name;
            resourceInputs["rotations"] = args?.rotations;
            resourceInputs["teamIds"] = args?.teamIds;
            resourceInputs["timezone"] = args?.timezone;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Schedule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Schedule resources.
 */
export interface ScheduleState {
    holidaysPublicConfig?: pulumi.Input<inputs.ScheduleHolidaysPublicConfig>;
    /**
     * Human readable name synced from external provider
     */
    name?: pulumi.Input<string>;
    rotations?: pulumi.Input<pulumi.Input<inputs.ScheduleRotation>[]>;
    /**
     * IDs of teams that own this schedule
     */
    teamIds?: pulumi.Input<pulumi.Input<string>[]>;
    timezone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Schedule resource.
 */
export interface ScheduleArgs {
    holidaysPublicConfig?: pulumi.Input<inputs.ScheduleHolidaysPublicConfig>;
    /**
     * Human readable name synced from external provider
     */
    name?: pulumi.Input<string>;
    rotations: pulumi.Input<pulumi.Input<inputs.ScheduleRotation>[]>;
    /**
     * IDs of teams that own this schedule
     */
    teamIds?: pulumi.Input<pulumi.Input<string>[]>;
    timezone: pulumi.Input<string>;
}
