// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Status extends pulumi.CustomResource {
    /**
     * Get an existing Status resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StatusState, opts?: pulumi.CustomResourceOptions): Status {
        return new Status(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/status:Status';

    /**
     * Returns true if the given object is an instance of Status.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Status {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Status.__pulumiType;
    }

    /**
     * What category of status it is. All statuses apart from live (renamed in the app to Active) and learning (renamed in the app to Post-incident) are managed by incident.io and cannot be configured. Possible values are: <span pulumi-lang-nodejs="`triage`" pulumi-lang-dotnet="`Triage`" pulumi-lang-go="`triage`" pulumi-lang-python="`triage`" pulumi-lang-yaml="`triage`" pulumi-lang-java="`triage`">`triage`</span>, <span pulumi-lang-nodejs="`declined`" pulumi-lang-dotnet="`Declined`" pulumi-lang-go="`declined`" pulumi-lang-python="`declined`" pulumi-lang-yaml="`declined`" pulumi-lang-java="`declined`">`declined`</span>, <span pulumi-lang-nodejs="`merged`" pulumi-lang-dotnet="`Merged`" pulumi-lang-go="`merged`" pulumi-lang-python="`merged`" pulumi-lang-yaml="`merged`" pulumi-lang-java="`merged`">`merged`</span>, <span pulumi-lang-nodejs="`canceled`" pulumi-lang-dotnet="`Canceled`" pulumi-lang-go="`canceled`" pulumi-lang-python="`canceled`" pulumi-lang-yaml="`canceled`" pulumi-lang-java="`canceled`">`canceled`</span>, <span pulumi-lang-nodejs="`live`" pulumi-lang-dotnet="`Live`" pulumi-lang-go="`live`" pulumi-lang-python="`live`" pulumi-lang-yaml="`live`" pulumi-lang-java="`live`">`live`</span>, <span pulumi-lang-nodejs="`learning`" pulumi-lang-dotnet="`Learning`" pulumi-lang-go="`learning`" pulumi-lang-python="`learning`" pulumi-lang-yaml="`learning`" pulumi-lang-java="`learning`">`learning`</span>, <span pulumi-lang-nodejs="`closed`" pulumi-lang-dotnet="`Closed`" pulumi-lang-go="`closed`" pulumi-lang-python="`closed`" pulumi-lang-yaml="`closed`" pulumi-lang-java="`closed`">`closed`</span>, <span pulumi-lang-nodejs="`paused`" pulumi-lang-dotnet="`Paused`" pulumi-lang-go="`paused`" pulumi-lang-python="`paused`" pulumi-lang-yaml="`paused`" pulumi-lang-java="`paused`">`paused`</span>.
     */
    declare public readonly category: pulumi.Output<string>;
    /**
     * Rich text description of the incident status
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Unique name of this status
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a Status resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StatusArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StatusArgs | StatusState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StatusState | undefined;
            resourceInputs["category"] = state?.category;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as StatusArgs | undefined;
            if (args?.category === undefined && !opts.urn) {
                throw new Error("Missing required property 'category'");
            }
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            resourceInputs["category"] = args?.category;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Status.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Status resources.
 */
export interface StatusState {
    /**
     * What category of status it is. All statuses apart from live (renamed in the app to Active) and learning (renamed in the app to Post-incident) are managed by incident.io and cannot be configured. Possible values are: <span pulumi-lang-nodejs="`triage`" pulumi-lang-dotnet="`Triage`" pulumi-lang-go="`triage`" pulumi-lang-python="`triage`" pulumi-lang-yaml="`triage`" pulumi-lang-java="`triage`">`triage`</span>, <span pulumi-lang-nodejs="`declined`" pulumi-lang-dotnet="`Declined`" pulumi-lang-go="`declined`" pulumi-lang-python="`declined`" pulumi-lang-yaml="`declined`" pulumi-lang-java="`declined`">`declined`</span>, <span pulumi-lang-nodejs="`merged`" pulumi-lang-dotnet="`Merged`" pulumi-lang-go="`merged`" pulumi-lang-python="`merged`" pulumi-lang-yaml="`merged`" pulumi-lang-java="`merged`">`merged`</span>, <span pulumi-lang-nodejs="`canceled`" pulumi-lang-dotnet="`Canceled`" pulumi-lang-go="`canceled`" pulumi-lang-python="`canceled`" pulumi-lang-yaml="`canceled`" pulumi-lang-java="`canceled`">`canceled`</span>, <span pulumi-lang-nodejs="`live`" pulumi-lang-dotnet="`Live`" pulumi-lang-go="`live`" pulumi-lang-python="`live`" pulumi-lang-yaml="`live`" pulumi-lang-java="`live`">`live`</span>, <span pulumi-lang-nodejs="`learning`" pulumi-lang-dotnet="`Learning`" pulumi-lang-go="`learning`" pulumi-lang-python="`learning`" pulumi-lang-yaml="`learning`" pulumi-lang-java="`learning`">`learning`</span>, <span pulumi-lang-nodejs="`closed`" pulumi-lang-dotnet="`Closed`" pulumi-lang-go="`closed`" pulumi-lang-python="`closed`" pulumi-lang-yaml="`closed`" pulumi-lang-java="`closed`">`closed`</span>, <span pulumi-lang-nodejs="`paused`" pulumi-lang-dotnet="`Paused`" pulumi-lang-go="`paused`" pulumi-lang-python="`paused`" pulumi-lang-yaml="`paused`" pulumi-lang-java="`paused`">`paused`</span>.
     */
    category?: pulumi.Input<string>;
    /**
     * Rich text description of the incident status
     */
    description?: pulumi.Input<string>;
    /**
     * Unique name of this status
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Status resource.
 */
export interface StatusArgs {
    /**
     * What category of status it is. All statuses apart from live (renamed in the app to Active) and learning (renamed in the app to Post-incident) are managed by incident.io and cannot be configured. Possible values are: <span pulumi-lang-nodejs="`triage`" pulumi-lang-dotnet="`Triage`" pulumi-lang-go="`triage`" pulumi-lang-python="`triage`" pulumi-lang-yaml="`triage`" pulumi-lang-java="`triage`">`triage`</span>, <span pulumi-lang-nodejs="`declined`" pulumi-lang-dotnet="`Declined`" pulumi-lang-go="`declined`" pulumi-lang-python="`declined`" pulumi-lang-yaml="`declined`" pulumi-lang-java="`declined`">`declined`</span>, <span pulumi-lang-nodejs="`merged`" pulumi-lang-dotnet="`Merged`" pulumi-lang-go="`merged`" pulumi-lang-python="`merged`" pulumi-lang-yaml="`merged`" pulumi-lang-java="`merged`">`merged`</span>, <span pulumi-lang-nodejs="`canceled`" pulumi-lang-dotnet="`Canceled`" pulumi-lang-go="`canceled`" pulumi-lang-python="`canceled`" pulumi-lang-yaml="`canceled`" pulumi-lang-java="`canceled`">`canceled`</span>, <span pulumi-lang-nodejs="`live`" pulumi-lang-dotnet="`Live`" pulumi-lang-go="`live`" pulumi-lang-python="`live`" pulumi-lang-yaml="`live`" pulumi-lang-java="`live`">`live`</span>, <span pulumi-lang-nodejs="`learning`" pulumi-lang-dotnet="`Learning`" pulumi-lang-go="`learning`" pulumi-lang-python="`learning`" pulumi-lang-yaml="`learning`" pulumi-lang-java="`learning`">`learning`</span>, <span pulumi-lang-nodejs="`closed`" pulumi-lang-dotnet="`Closed`" pulumi-lang-go="`closed`" pulumi-lang-python="`closed`" pulumi-lang-yaml="`closed`" pulumi-lang-java="`closed`">`closed`</span>, <span pulumi-lang-nodejs="`paused`" pulumi-lang-dotnet="`Paused`" pulumi-lang-go="`paused`" pulumi-lang-python="`paused`" pulumi-lang-yaml="`paused`" pulumi-lang-java="`paused`">`paused`</span>.
     */
    category: pulumi.Input<string>;
    /**
     * Rich text description of the incident status
     */
    description: pulumi.Input<string>;
    /**
     * Unique name of this status
     */
    name?: pulumi.Input<string>;
}
