// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Workflow extends pulumi.CustomResource {
    /**
     * Get an existing Workflow resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkflowState, opts?: pulumi.CustomResourceOptions): Workflow {
        return new Workflow(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'incident:index/workflow:Workflow';

    /**
     * Returns true if the given object is an instance of Workflow.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Workflow {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Workflow.__pulumiType;
    }

    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    declare public readonly conditionGroups: pulumi.Output<outputs.WorkflowConditionGroup[]>;
    /**
     * Whether to continue executing the workflow if a step fails
     */
    declare public readonly continueOnStepError: pulumi.Output<boolean>;
    /**
     * Configuration controlling workflow delay behaviour
     */
    declare public readonly delay: pulumi.Output<outputs.WorkflowDelay | undefined>;
    /**
     * The expressions to be prepared for use by steps and conditions
     */
    declare public readonly expressions: pulumi.Output<outputs.WorkflowExpression[]>;
    /**
     * Folder to display the workflow in
     */
    declare public readonly folder: pulumi.Output<string | undefined>;
    /**
     * Whether to include private escalations
     */
    declare public readonly includePrivateEscalations: pulumi.Output<boolean>;
    /**
     * Whether to include private incidents
     */
    declare public readonly includePrivateIncidents: pulumi.Output<boolean>;
    /**
     * Name provided by the user when creating the workflow
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * This workflow will run 'once for' a list of references
     */
    declare public readonly onceFors: pulumi.Output<string[]>;
    /**
     * Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
     */
    declare public readonly runsOnIncidentModes: pulumi.Output<string[]>;
    /**
     * Which incidents should the workflow be applied to?. Possible values are: <span pulumi-lang-nodejs="`newlyCreated`" pulumi-lang-dotnet="`NewlyCreated`" pulumi-lang-go="`newlyCreated`" pulumi-lang-python="`newly_created`" pulumi-lang-yaml="`newlyCreated`" pulumi-lang-java="`newlyCreated`">`newly_created`</span>, <span pulumi-lang-nodejs="`newlyCreatedAndActive`" pulumi-lang-dotnet="`NewlyCreatedAndActive`" pulumi-lang-go="`newlyCreatedAndActive`" pulumi-lang-python="`newly_created_and_active`" pulumi-lang-yaml="`newlyCreatedAndActive`" pulumi-lang-java="`newlyCreatedAndActive`">`newly_created_and_active`</span>.
     */
    declare public readonly runsOnIncidents: pulumi.Output<string>;
    /**
     * The shortform used to trigger this workflow (only applicable for manual triggers)
     */
    declare public readonly shortform: pulumi.Output<string | undefined>;
    /**
     * What state this workflow is in. Possible values are: <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>, <span pulumi-lang-nodejs="`draft`" pulumi-lang-dotnet="`Draft`" pulumi-lang-go="`draft`" pulumi-lang-python="`draft`" pulumi-lang-yaml="`draft`" pulumi-lang-java="`draft`">`draft`</span>, <span pulumi-lang-nodejs="`error`" pulumi-lang-dotnet="`Error`" pulumi-lang-go="`error`" pulumi-lang-python="`error`" pulumi-lang-yaml="`error`" pulumi-lang-java="`error`">`error`</span>.
     */
    declare public readonly state: pulumi.Output<string>;
    /**
     * Steps that are executed as part of the workflow
     */
    declare public readonly steps: pulumi.Output<outputs.WorkflowStep[]>;
    /**
     * Unique name of the trigger
     */
    declare public readonly trigger: pulumi.Output<string>;

    /**
     * Create a Workflow resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkflowArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkflowArgs | WorkflowState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkflowState | undefined;
            resourceInputs["conditionGroups"] = state?.conditionGroups;
            resourceInputs["continueOnStepError"] = state?.continueOnStepError;
            resourceInputs["delay"] = state?.delay;
            resourceInputs["expressions"] = state?.expressions;
            resourceInputs["folder"] = state?.folder;
            resourceInputs["includePrivateEscalations"] = state?.includePrivateEscalations;
            resourceInputs["includePrivateIncidents"] = state?.includePrivateIncidents;
            resourceInputs["name"] = state?.name;
            resourceInputs["onceFors"] = state?.onceFors;
            resourceInputs["runsOnIncidentModes"] = state?.runsOnIncidentModes;
            resourceInputs["runsOnIncidents"] = state?.runsOnIncidents;
            resourceInputs["shortform"] = state?.shortform;
            resourceInputs["state"] = state?.state;
            resourceInputs["steps"] = state?.steps;
            resourceInputs["trigger"] = state?.trigger;
        } else {
            const args = argsOrState as WorkflowArgs | undefined;
            if (args?.conditionGroups === undefined && !opts.urn) {
                throw new Error("Missing required property 'conditionGroups'");
            }
            if (args?.continueOnStepError === undefined && !opts.urn) {
                throw new Error("Missing required property 'continueOnStepError'");
            }
            if (args?.expressions === undefined && !opts.urn) {
                throw new Error("Missing required property 'expressions'");
            }
            if (args?.includePrivateIncidents === undefined && !opts.urn) {
                throw new Error("Missing required property 'includePrivateIncidents'");
            }
            if (args?.onceFors === undefined && !opts.urn) {
                throw new Error("Missing required property 'onceFors'");
            }
            if (args?.runsOnIncidentModes === undefined && !opts.urn) {
                throw new Error("Missing required property 'runsOnIncidentModes'");
            }
            if (args?.runsOnIncidents === undefined && !opts.urn) {
                throw new Error("Missing required property 'runsOnIncidents'");
            }
            if (args?.state === undefined && !opts.urn) {
                throw new Error("Missing required property 'state'");
            }
            if (args?.steps === undefined && !opts.urn) {
                throw new Error("Missing required property 'steps'");
            }
            if (args?.trigger === undefined && !opts.urn) {
                throw new Error("Missing required property 'trigger'");
            }
            resourceInputs["conditionGroups"] = args?.conditionGroups;
            resourceInputs["continueOnStepError"] = args?.continueOnStepError;
            resourceInputs["delay"] = args?.delay;
            resourceInputs["expressions"] = args?.expressions;
            resourceInputs["folder"] = args?.folder;
            resourceInputs["includePrivateEscalations"] = args?.includePrivateEscalations;
            resourceInputs["includePrivateIncidents"] = args?.includePrivateIncidents;
            resourceInputs["name"] = args?.name;
            resourceInputs["onceFors"] = args?.onceFors;
            resourceInputs["runsOnIncidentModes"] = args?.runsOnIncidentModes;
            resourceInputs["runsOnIncidents"] = args?.runsOnIncidents;
            resourceInputs["shortform"] = args?.shortform;
            resourceInputs["state"] = args?.state;
            resourceInputs["steps"] = args?.steps;
            resourceInputs["trigger"] = args?.trigger;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Workflow.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Workflow resources.
 */
export interface WorkflowState {
    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    conditionGroups?: pulumi.Input<pulumi.Input<inputs.WorkflowConditionGroup>[]>;
    /**
     * Whether to continue executing the workflow if a step fails
     */
    continueOnStepError?: pulumi.Input<boolean>;
    /**
     * Configuration controlling workflow delay behaviour
     */
    delay?: pulumi.Input<inputs.WorkflowDelay>;
    /**
     * The expressions to be prepared for use by steps and conditions
     */
    expressions?: pulumi.Input<pulumi.Input<inputs.WorkflowExpression>[]>;
    /**
     * Folder to display the workflow in
     */
    folder?: pulumi.Input<string>;
    /**
     * Whether to include private escalations
     */
    includePrivateEscalations?: pulumi.Input<boolean>;
    /**
     * Whether to include private incidents
     */
    includePrivateIncidents?: pulumi.Input<boolean>;
    /**
     * Name provided by the user when creating the workflow
     */
    name?: pulumi.Input<string>;
    /**
     * This workflow will run 'once for' a list of references
     */
    onceFors?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
     */
    runsOnIncidentModes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Which incidents should the workflow be applied to?. Possible values are: <span pulumi-lang-nodejs="`newlyCreated`" pulumi-lang-dotnet="`NewlyCreated`" pulumi-lang-go="`newlyCreated`" pulumi-lang-python="`newly_created`" pulumi-lang-yaml="`newlyCreated`" pulumi-lang-java="`newlyCreated`">`newly_created`</span>, <span pulumi-lang-nodejs="`newlyCreatedAndActive`" pulumi-lang-dotnet="`NewlyCreatedAndActive`" pulumi-lang-go="`newlyCreatedAndActive`" pulumi-lang-python="`newly_created_and_active`" pulumi-lang-yaml="`newlyCreatedAndActive`" pulumi-lang-java="`newlyCreatedAndActive`">`newly_created_and_active`</span>.
     */
    runsOnIncidents?: pulumi.Input<string>;
    /**
     * The shortform used to trigger this workflow (only applicable for manual triggers)
     */
    shortform?: pulumi.Input<string>;
    /**
     * What state this workflow is in. Possible values are: <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>, <span pulumi-lang-nodejs="`draft`" pulumi-lang-dotnet="`Draft`" pulumi-lang-go="`draft`" pulumi-lang-python="`draft`" pulumi-lang-yaml="`draft`" pulumi-lang-java="`draft`">`draft`</span>, <span pulumi-lang-nodejs="`error`" pulumi-lang-dotnet="`Error`" pulumi-lang-go="`error`" pulumi-lang-python="`error`" pulumi-lang-yaml="`error`" pulumi-lang-java="`error`">`error`</span>.
     */
    state?: pulumi.Input<string>;
    /**
     * Steps that are executed as part of the workflow
     */
    steps?: pulumi.Input<pulumi.Input<inputs.WorkflowStep>[]>;
    /**
     * Unique name of the trigger
     */
    trigger?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Workflow resource.
 */
export interface WorkflowArgs {
    /**
     * Groups of prerequisite conditions. All conditions in at least one group must be satisfied
     */
    conditionGroups: pulumi.Input<pulumi.Input<inputs.WorkflowConditionGroup>[]>;
    /**
     * Whether to continue executing the workflow if a step fails
     */
    continueOnStepError: pulumi.Input<boolean>;
    /**
     * Configuration controlling workflow delay behaviour
     */
    delay?: pulumi.Input<inputs.WorkflowDelay>;
    /**
     * The expressions to be prepared for use by steps and conditions
     */
    expressions: pulumi.Input<pulumi.Input<inputs.WorkflowExpression>[]>;
    /**
     * Folder to display the workflow in
     */
    folder?: pulumi.Input<string>;
    /**
     * Whether to include private escalations
     */
    includePrivateEscalations?: pulumi.Input<boolean>;
    /**
     * Whether to include private incidents
     */
    includePrivateIncidents: pulumi.Input<boolean>;
    /**
     * Name provided by the user when creating the workflow
     */
    name?: pulumi.Input<string>;
    /**
     * This workflow will run 'once for' a list of references
     */
    onceFors: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
     */
    runsOnIncidentModes: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Which incidents should the workflow be applied to?. Possible values are: <span pulumi-lang-nodejs="`newlyCreated`" pulumi-lang-dotnet="`NewlyCreated`" pulumi-lang-go="`newlyCreated`" pulumi-lang-python="`newly_created`" pulumi-lang-yaml="`newlyCreated`" pulumi-lang-java="`newlyCreated`">`newly_created`</span>, <span pulumi-lang-nodejs="`newlyCreatedAndActive`" pulumi-lang-dotnet="`NewlyCreatedAndActive`" pulumi-lang-go="`newlyCreatedAndActive`" pulumi-lang-python="`newly_created_and_active`" pulumi-lang-yaml="`newlyCreatedAndActive`" pulumi-lang-java="`newlyCreatedAndActive`">`newly_created_and_active`</span>.
     */
    runsOnIncidents: pulumi.Input<string>;
    /**
     * The shortform used to trigger this workflow (only applicable for manual triggers)
     */
    shortform?: pulumi.Input<string>;
    /**
     * What state this workflow is in. Possible values are: <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>, <span pulumi-lang-nodejs="`draft`" pulumi-lang-dotnet="`Draft`" pulumi-lang-go="`draft`" pulumi-lang-python="`draft`" pulumi-lang-yaml="`draft`" pulumi-lang-java="`draft`">`draft`</span>, <span pulumi-lang-nodejs="`error`" pulumi-lang-dotnet="`Error`" pulumi-lang-go="`error`" pulumi-lang-python="`error`" pulumi-lang-yaml="`error`" pulumi-lang-java="`error`">`error`</span>.
     */
    state: pulumi.Input<string>;
    /**
     * Steps that are executed as part of the workflow
     */
    steps: pulumi.Input<pulumi.Input<inputs.WorkflowStep>[]>;
    /**
     * Unique name of the trigger
     */
    trigger: pulumi.Input<string>;
}
